"""add_intern_status

Revision ID: eeee82571332
Revises: 3a341a628c67
Create Date: 2026-05-10 10:44:22.732116

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'eeee82571332'
down_revision: Union[str, None] = '3a341a628c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interns', sa.Column('status', sa.String(), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interns', 'status')
    # ### end Alembic commands ###
